# 開發環境覆蓋配置
# 這個文件會自動被 docker-compose 加載
# 用於開發時的特殊配置

version: '3.8'

services:
  # 開發時可以直接暴露後端端口用於調試
  backend:
    ports:
      - "8081:8081"
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug

  # 開發時可以直接暴露前端端口
  frontend:
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost/api

  # nginx 開發配置
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80