services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rt
      POSTGRES_USER: user
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_URL=postgres://user:postgres@db:5432/rt
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5174:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/ssl/certs:ro
      - ./nginx/ssl:/etc/ssl/private:ro
    networks:
      - app-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: